### ISSUE TITLE
"npm start" breaks

### ISSUE THREAD

**Issue by LizardLeliel** [Glavin001/BurntChrome#29]
After pulling from this branch, npm install has been called (called it after it failed the second time), and it gives many errors. Here's the full output:

```
$ npm start

> burntchrome@1.0.0 start C:\Users\Evan\Documents\Coding\web\BC
> npm-run-all compile watch


> burntchrome@1.0.0 compile C:\Users\Evan\Documents\Coding\web\BC
> npm-run-all compile:deps compile:src




> burntchrome@1.0.0 compile:deps C:\Users\Evan\Documents\Coding\web\BC
> npm-run-all compile:deps:*


> burntchrome@1.0.0 compile:deps:css C:\Users\Evan\Documents\Coding\web\BC
> npm-run-all compile:deps:css:*


> burntchrome@1.0.0 compile:deps:css:content C:\Users\Evan\Documents\Coding\web\BC
> cleancss --source-map-inline-sources -o extension/dist/deps-content.css ./bower_components/chrome-bootstrap/chrome-bootstrap.css ./bower_components/intro.js/introjs.css


> burntchrome@1.0.0 compile:deps:js C:\Users\Evan\Documents\Coding\web\BC
> npm-run-all compile:deps:js:*


> burntchrome@1.0.0 compile:deps:js:content C:\Users\Evan\Documents\Coding\web\BC
> uglifyjs ./bower_components/jquery/dist/jquery.js ./bower_components/lodash/dist/lodash.js ./node_modules/devtools-detect/index.js ./bower_components/handlebars/handlebars.min.js ./bower_components/intro.js/intro.js --compress --output extension/dist/deps-content.js

(node) util.error is deprecated. Use console.error instead.
WARN: Dropping unused function argument collection [./bower_components/lodash/dist/lodash.js:3131,60]
WARN: Dropping unused function argument key [./bower_components/lodash/dist/lodash.js:3131,55]
WARN: Dropping unused function argument g [./bower_components/handlebars/handlebars.min.js:27,17086]
WARN: Dropping unused function argument b [./bower_components/handlebars/handlebars.min.js:28,452]
WARN: Dropping unused function argument d [./bower_components/handlebars/handlebars.min.js:28,6069]
WARN: Non-strict equality against boolean: == true [./bower_components/intro.js/intro.js:199,32]
WARN: Dropping unused function argument e [./bower_components/intro.js/intro.js:242,32]
WARN: Side effects in initialization of unused variable skipButton [./bower_components/intro.js/intro.js:195,10]
WARN: Side effects in initialization of unused variable nextStepButton [./bower_components/intro.js/intro.js:196,10]
WARN: Non-strict equality against boolean: == true [./bower_components/intro.js/intro.js:506,25]
WARN: Non-strict equality against boolean: == true [./bower_components/intro.js/intro.js:911,10]
WARN: Side effects in initialization of unused variable elementPosition [./bower_components/intro.js/intro.js:750,8]
WARN: Non-strict equality against boolean: == true [./bower_components/intro.js/intro.js:1166,10]
WARN: Dropping unused variable self [./bower_components/intro.js/intro.js:1209,8]

> burntchrome@1.0.0 compile:deps:js:background C:\Users\Evan\Documents\Coding\web\BC
> uglifyjs ./bower_components/lodash/dist/lodash.js ./bower_components/crypto-js/crypto-js.js ./node_modules/minimatch/minimatch.js --compress --output extension/dist/deps-background.js

(node) util.error is deprecated. Use console.error instead.
ERROR: can't read file: ./node_modules/minimatch/minimatch.js

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "compile:deps:js:background"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! burntchrome@1.0.0 compile:deps:js:background: `uglifyjs ./bower_components/lodash/dist/lodash.js ./bower_components/crypto-js/crypto-js.js ./node_modules/minimatch/minimatch.js --compress --output extension/dist/deps-background.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the burntchrome@1.0.0 compile:deps:js:background script 'uglifyjs ./bower_components/lodash/dist/lodash.js ./bower_components/crypto-js/crypto-js.js ./node_modules/minimatch/minimatch.js --compress --output extension/dist/deps-background.js'.
npm ERR! This is most likely a problem with the burntchrome package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     uglifyjs ./bower_components/lodash/dist/lodash.js ./bower_components/crypto-js/crypto-js.js ./node_modules/minimatch/minimatch.js --compress --output extension/dist/deps-background.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls burntchrome
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Evan\Documents\Coding\web\BC\npm-debug.log
ERROR: compile:deps:js:background: None-Zero Exit(1);

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "compile:deps:js"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! burntchrome@1.0.0 compile:deps:js: `npm-run-all compile:deps:js:*`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the burntchrome@1.0.0 compile:deps:js script 'npm-run-all compile:deps:js:*'.
npm ERR! This is most likely a problem with the burntchrome package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all compile:deps:js:*
npm ERR! You can get their info via:
npm ERR!     npm owner ls burntchrome
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Evan\Documents\Coding\web\BC\npm-debug.log
ERROR: compile:deps:js: None-Zero Exit(1);

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "compile:deps"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! burntchrome@1.0.0 compile:deps: `npm-run-all compile:deps:*`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the burntchrome@1.0.0 compile:deps script 'npm-run-all compile:deps:*'.
npm ERR! This is most likely a problem with the burntchrome package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all compile:deps:*
npm ERR! You can get their info via:
npm ERR!     npm owner ls burntchrome
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Evan\Documents\Coding\web\BC\npm-debug.log
ERROR: compile:deps: None-Zero Exit(1);

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "compile"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! burntchrome@1.0.0 compile: `npm-run-all compile:deps compile:src`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the burntchrome@1.0.0 compile script 'npm-run-all compile:deps compile:src'.
npm ERR! This is most likely a problem with the burntchrome package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all compile:deps compile:src
npm ERR! You can get their info via:
npm ERR!     npm owner ls burntchrome
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Evan\Documents\Coding\web\BC\npm-debug.log
ERROR: compile: None-Zero Exit(1);

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! burntchrome@1.0.0 start: `npm-run-all compile watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the burntchrome@1.0.0 start script 'npm-run-all compile watch'.
npm ERR! This is most likely a problem with the burntchrome package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all compile watch
npm ERR! You can get their info via:
npm ERR!     npm owner ls burntchrome
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Evan\Documents\Coding\web\BC\npm-debug.log
```

npm-debug.log:

```

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.14.12
3 info using node@v4.3.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart burntchrome@1.0.0
6 info start burntchrome@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info burntchrome@1.0.0 Failed to exec start script
9 verbose stack Error: burntchrome@1.0.0 start: `npm-run-all compile watch`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:821:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid burntchrome@1.0.0
11 verbose cwd C:\Users\Evan\Documents\Coding\web\BC
12 error Windows_NT 6.3.9600
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v4.3.0
15 error npm  v2.14.12
16 error code ELIFECYCLE
17 error burntchrome@1.0.0 start: `npm-run-all compile watch`
17 error Exit status 1
18 error Failed at the burntchrome@1.0.0 start script 'npm-run-all compile watch'.
18 error This is most likely a problem with the burntchrome package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm-run-all compile watch
18 error You can get their info via:
18 error     npm owner ls burntchrome
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by Glavin001** [comment]
I see in your logs:

```
ERROR: can't read file: ./node_modules/minimatch/minimatch.js
```

Can you confirm that `minimatch` was successfully installed in `./node_modules/minimatch/`?

**Comment by LizardLeliel** [comment]
Its not there. Do i need to npm install minimatch?

**Comment by Glavin001** [comment]
Did you run `npm install` ? Yes, you should.

**Comment by LizardLeliel** [comment]
I did run npm install, it didn't work.

However I did run "npm install minimatch", and now it is working.

Thank you.

**Comment by Glavin001** [comment]
`npm install` did not work as in it failed? Or as in this error still happened?

I have confirmed that `minimatch` is added as dependency to Bower: https://github.com/Glavin001/BurntChrome/commit/6241c16027c343d1a7ccb96641227c0dd6ab2927#diff-0a08a7565aba4405282251491979bb6bR28
So since you were having problems with Bower, run `bower install`.

**Comment by LizardLeliel** [comment]
npm install did everything as it did, but did not fix npm start.

After doing npm install minimatch, npm start works.

**Comment by Glavin001** [comment]
`npm install minimatch` actually should not fix the problem, as I used the bower version. So that does not make sense and at most was coincidental.

**Comment by Glavin001** [comment]
Oh no! I found the bug.

I used Bower to install and it was using npm's copy in the build script, which is why it was failing. It was a typo. I'll fix.
